### ISSUE TITLE
Server error "status_code": 500

### ISSUE THREAD

**Issue by JuanCarrillo** [ropensci/paleobioDB#56] opened 2023-08-02 07:47 UTC
Hello paleobioDB team

When trying to get fossil occurrences from the PBDB using the package I am getting a server error I didn’t get before. I think is related with the large amount of occurrences I am trying to download (Neogene mammals from North America), because when trying smaller time bins (e.g. late Pleistocene) my code works just fine.

The error message I am getting is the following:

```
Error in .extract_response_body(response) :
  Error in API response. The server returned a status 500, which indicates that
                                                something went wrong with your request. In order to debug the problem you may find
                                                usefull information in the following server response:
{ "status_code": 500,
"errors": ["A server error occurred.  Please contact the server administrator."] }
```

I am using R version 4.2.2 and my computer is a Mac, with apple M1, macOS 13.5. The code I am using is as follows:

```
# get the names and IDs of the non terrestrial clades to be excluded
non_terrestrial <- pbdb_taxa(name = c("Pinnipedia", "Pinnipedimorpha","Odobenidae","Cetacea",
                                  "Sirenia","Desmostylia","Thalassocnus","Lontra felina",
                                  "Enhydra lutris","Ursus maritimus"), vocab = "pbdb")
 
# Download the occurrences of NA Neogene mammals, excluding non-terrestrial mammals
NA_mammals<-pbdb_occurrences(base_name="Mammalia",vocab="pbdb",continent="NOA",
                             ident="latest",limit="all",max_ma=23.03,min_ma=0.129,timerule="contain",
                             show=c("ident","phylo","coords","loc","paleoloc","time","strat","stratext"),
                             exclude_id=non_terrestrial$taxon_no)
```

Many thanks for your work on maintaining this package, it is very useful! 

Best regards, 

Juan Carrillo

**Comment by castroinsua** [comment] 2024-02-06 09:41
The 500 status code indicates an internal server error, and we cannot know exactly why it happened. In some cases you can simply try at a later time and your query will work, but it could also be due to a bug in the server-side code. 

Although you were using version 1.1 of the API, I could reproduce the same problem you reported in version 1.2 by replacing some of the parameters that changed between versions with equivalent ones. In your specific query, there seems to be some problem when you specify `"paleoloc"` as a value in the `show` parameter in combination with `continent = "NOA"`. Here you could work around this simply by using `show = "full"` to get paleogeographic information, although maybe not for all records.

Since this is a problem with the server, and not with the package, I will close this issue. But maybe this should be reported to the PBDB server administrators.

**Closed by castroinsua** 2024-02-06 09:41 UTC
