### ISSUE TITLE
basic example fails

### ISSUE THREAD

**Issue by psmits** [ropensci/paleobioDB#36] opened 2018-11-13 21:45 UTC
Hi there,

I was playing around with the function and tried using the README examples and I get an error message with the first function call.

`canidae<-  pbdb_occurrences (limit="all",
                             base_name="canidae", vocab="pbdb",
                             interval="Quaternary",             
                             show=c("coords", "phylo", "ident"))`

Error in !sapply(data, function(l) is.null(l) | (ncol(l) == 0) | (nrow(l) ==  :    
  invalid argument type 

Any idea what could be causing this?

Cheers

**Comment by SaraVarela** [comment] 2018-11-16 10:35
Hi @psmits, 
yes, you are right. Let me check this during the weekend.
(or feel free to explore it yourself and send us a pull request if you find the problem)
and thanks for the feedback!
Sara

**Comment by japilo** [comment] 2018-12-10 15:49
I have had the same issue while trying to use the package. I did a traceback and the problem seems to be coming from the `smartbind()` call in the `.make_data_frame` function.

**Comment by DrPronghorn** [comment] 2019-02-19 19:32
Has there been any progress on this issue? Or is there a workaround?

**Comment by javigzz** [comment] 2019-02-22 22:03
Hello @psmits, @DrPronghorn, @japilo thanks for reporting the issue and sorry for the delay. The issue is already fixed in this repository but not in the version in CRAN. I will create a new release to CRAN ASAP including the patch in https://github.com/ropensci/paleobioDB/pull/35. In the meantime you may just install the github version by:

```
install.packages("devtools")
library(devtools)
install_github("ropensci/paleobioDB")
```

**Closed by javigzz** 2019-02-22 22:03 UTC
