### ISSUE TITLE
None of the query functions work

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/paleobioDB#48] opened 2020-10-09 04:33 UTC
I have code from this package that has worked for years, and now none of it does. 

The vignette/documentation code also doesn't work, everytime I use the pbdb_occurrences() function it returns:

Error in .extract_response_body(response) : 
  Error in API response. The server returned a status 301, which indicates that 
			something went wrong with your request. 
In order to debug the problem you may find
			usefull information in the following server response:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

I assume this means the API has a different path now that hasn't been added into the package API wrapper functions or something???

**Comment by javigzz** [comment] 2020-10-10 16:05
Closing this as duplicate of the next one. Answering in #49

**Closed by javigzz** 2020-10-10 16:05 UTC
